/**
 * Sanctuary Hub — asset download pipeline.
 *
 * Downloads each asset to /tmp/sanctuary-assets/ and writes manifest.json.
 * The companion `upload-assets-curl.sh` (generated by Bash + a Cloudflare
 * API token created via the OAuth MCP) PUTs each file to R2.
 *
 * Why this split: the Cloudflare MCP execute environment blocks ALL
 * outbound fetch() (egress denied — even example.com 403s), so we cannot
 * download assets from inside the MCP runtime. Uploads happen separately
 * via the native R2 API with a 1-hour scoped token.
 *
 * Asset sourcing strategy:
 *   - Class portraits + most skill icons: real D4 game art from
 *     `sunderarmor.com/DIABLO4/...` (d4builds.gg's CDN, public).
 *   - Items, events, UI chrome, and unmapped skill archetypes: game-icons
 *     SVGs (MIT licensed) from github.com/game-icons/icons.
 *
 * Run: tsx scripts/upload-assets.ts
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const OUT_DIR = '/tmp/sanctuary-assets';
const USER_AGENT =
  'Mozilla/5.0 SanctuaryHub/1.0 (fan site, educational capstone project)';

// ───────────────────────────────────────────────────────────────
// URL helpers
// ───────────────────────────────────────────────────────────────

const SUNDER = (folder: string, slug: string) =>
  `https://sunderarmor.com/DIABLO4/${folder}/${slug}.png`;

const GI = (artist: string, slug: string) =>
  `https://raw.githubusercontent.com/game-icons/icons/master/${artist}/${slug}.svg`;

// Fandom Wiki CDN. Note: although URLs end in .png/.jpg, the CDN always
// serves WebP regardless of Accept header.
const FANDOM = (path: string) =>
  `https://static.wikia.nocookie.net/diablo/images/${path}`;

// ───────────────────────────────────────────────────────────────
// Source registry — primary (real D4 PNG, ideally) → fallback (SVG)
// ───────────────────────────────────────────────────────────────

interface Variant {
  url: string;
  ext: 'png' | 'svg' | 'jpg' | 'webp';
  contentType: string;
}

interface Source {
  /** Logical key without extension, e.g. `classes/barbarian`. */
  base: string;
  /** Ordered list of candidates. First successful fetch wins. */
  variants: Variant[];
}

const png  = (url: string): Variant => ({ url, ext: 'png',  contentType: 'image/png' });
const svg  = (url: string): Variant => ({ url, ext: 'svg',  contentType: 'image/svg+xml' });
const webp = (url: string): Variant => ({ url, ext: 'webp', contentType: 'image/webp' });

// Fandom Wiki has real Blizzard D4 promo art for each class. Falls back to
// d4builds' planner icon, then a thematic game-icons SVG.
const CLASS_FANDOM: Record<string, string> = {
  barbarian:   'b/b7/D4_Barbarian.png/revision/latest?cb=20191103014800',
  druid:       'f/fa/D4_Druid.png/revision/latest?cb=20191103014820',
  necromancer: 'f/fe/NecromancerD4-home.jpg/revision/latest?cb=20220623130841',
  rogue:       'f/fa/D4_Rogue_key_art.png/revision/latest?cb=20210223125003',
  sorcerer:    'c/c9/D4_Sorceress.png/revision/latest?cb=20191103014843',
  spiritborn:  'b/bc/Spiritborn2.jpg/revision/latest?cb=20240616083551',
  paladin:     'c/ce/Paladin_D4-cncpt1.jpg/revision/latest?cb=20260518124933',
};

const CLASS_SOURCES: Source[] = (
  ['barbarian', 'druid', 'necromancer', 'rogue', 'sorcerer', 'spiritborn', 'paladin'] as const
).map((c) => ({
  base: `classes/${c}`,
  variants: [
    webp(FANDOM(CLASS_FANDOM[c])),     // real Blizzard promo art
    png(SUNDER('Classes/2', c)),       // d4builds planner icon
    svg(GI('lorc', c === 'barbarian' ? 'muscle-up'
        : c === 'druid' ? 'wolf-head'
        : c === 'necromancer' ? 'skull-crack'
        : c === 'rogue' ? 'hood'
        : c === 'sorcerer' ? 'lightning-storm'
        : c === 'spiritborn' ? 'eagle-emblem'
        : 'angel-wings')),
  ],
}));

// Real D4 inventory icons for unique + mythic items, sourced from Fandom Wiki.
// Keyed by the canonical item name in our seed schema.
const UNIQUE_FANDOM: Record<string, string> = {
  // Mythic
  "Tyrael's Might":           '0/02/Tyrael%27s_Might-D4.jpg/revision/latest?cb=20240322091756',
  "Andariel's Visage":        '3/33/Andariel%27s_Visage-D4.jpg/revision/latest?cb=20230926125338',
  "Harlequin Crest":          'a/a1/Harlequin_Crest-D4.jpg/revision/latest?cb=20230427071316',
  "Melted Heart of Selig":    '4/4c/Melted_Heart_of_Selig.jpg/revision/latest?cb=20231101080229',
  "Ring of Starless Skies":   '2/2f/Ring_of_Starless_Skies.jpg/revision/latest?cb=20230901003112',
  "Doombringer":              'e/eb/Doombringer-D4.jpg/revision/latest?cb=20231021074456',
  // Shako is the community nickname for Harlequin Crest — share the icon.
  "Shako":                    'a/a1/Harlequin_Crest-D4.jpg/revision/latest?cb=20230427071316',
  // Unique weapons / armor
  "Azurewrath":               'b/be/Azurewrath-D4.jpg/revision/latest?cb=20230814125123',
  "Fleshrender":              'c/c0/Fleshrender-D4.jpg/revision/latest?cb=20230814125957',
  "Paingorger's Gauntlets":   '9/94/Paingorger%27s_Gauntlets.jpg/revision/latest?cb=20240430232700',
  "Temerity":                 'f/f6/Temerity.jpg/revision/latest?cb=20230427075505',
  "Arreat's Bearing":         '6/6f/Arreat%27s_Bearing.jpg/revision/latest?cb=20240516120510',
  "Rage of Harrogath":        '9/9a/Rage_of_Harrogath.jpg/revision/latest?cb=20231101113536',
  "Ancients' Oath":           '3/39/Ancient%27s_Oath.jpg/revision/latest?cb=20231111030105',
  "Greatstaff of the Crone":  'e/e3/Greatstaff_of_the_Crone.jpg/revision/latest?cb=20231003222746',
  "Waxing Gibbous":           '6/6b/Waxing_Gibbous.jpg/revision/latest?cb=20240414102850',
  "Black River":              '4/43/Black_River.jpg/revision/latest?cb=20231004031720',
  "Howl from Below":          'e/e7/Howl_from_Below.jpg/revision/latest?cb=20231008081935',
  "Word of Hakan":            '3/34/Word_of_Hakan.jpg/revision/latest?cb=20230427082533',
  "Condemnation":             '8/89/Condemnation.jpg/revision/latest?cb=20230820091102',
  "Grasp of Shadow":          '1/1e/Grasp_of_Shadow.jpg/revision/latest?cb=20240414212321',
  "Iceheart Brais":           'c/c0/Iceheart_Brais.jpg/revision/latest?cb=20240414212731',
  "Tal Rasha's Iridescent Loop": '6/6e/Tal_Rasha%27s_Iridescent_Loop.jpg/revision/latest?cb=20231110104524',
  "Staff of Lam Esen":        '3/3b/Staff_of_Lam_Esen.jpg/revision/latest?cb=20231111035613',
  "Fractured Winterglass":    'e/e6/Fractured_Winterglass.png/revision/latest?cb=20250911232617',
  // 3 items had no Fandom article (Grandfather, Mantle of the Mountain,
  // Blood Artisan's Cuirass) — they fall back to type icons at runtime.
};

function slugify(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '');
}

const UNIQUE_SOURCES: Source[] = Object.entries(UNIQUE_FANDOM).map(
  ([name, path]) => ({
    base: `uniques/${slugify(name)}`,
    variants: [webp(FANDOM(path))],
  }),
);

const ITEM_SOURCES: Source[] = [
  // Item type icons — game-icons (no real D4 source exposes these)
  { base: 'items/weapon',  variants: [svg(GI('lorc', 'broadsword'))] },
  { base: 'items/axe',     variants: [svg(GI('lorc', 'battle-axe'))] },
  { base: 'items/mace',    variants: [svg(GI('lorc', 'spiked-mace'))] },
  { base: 'items/scythe',  variants: [svg(GI('lorc', 'scythe'))] },
  { base: 'items/staff',   variants: [svg(GI('lorc', 'wizard-staff'))] },
  { base: 'items/bow',     variants: [svg(GI('lorc', 'bowman'))] },
  { base: 'items/dagger',  variants: [svg(GI('lorc', 'plain-dagger'))] },
  { base: 'items/wand',    variants: [svg(GI('lorc', 'fairy-wand'))] },
  { base: 'items/helm',    variants: [svg(GI('lorc', 'visored-helm'))] },
  { base: 'items/chest',   variants: [svg(GI('lorc', 'breastplate'))] },
  { base: 'items/gloves',  variants: [svg(GI('delapouite', 'gauntlet'))] },
  { base: 'items/boots',   variants: [svg(GI('lorc', 'boots'))] },
  { base: 'items/pants',   variants: [svg(GI('delapouite', 'leg-armor'))] },
  { base: 'items/offhand', variants: [svg(GI('sbed', 'shield'))] },
  { base: 'items/jewelry', variants: [svg(GI('lorc', 'emerald'))] },
  { base: 'items/amulet',  variants: [svg(GI('lorc', 'gem-pendant'))] },
  { base: 'items/mythic',  variants: [svg(GI('lorc', 'crowned-heart'))] },
  { base: 'items/unique',  variants: [svg(GI('lorc', 'shining-sword'))] },
];

// Skill archetypes mapped to real D4 skill icons where possible.
const SKILL_SOURCES: Source[] = [
  // Generic types — no D4 equivalent, use game-icons
  { base: 'skills/active',   variants: [svg(GI('lorc', 'crossed-swords'))] },
  { base: 'skills/passive',  variants: [svg(GI('sbed', 'shield'))] },
  { base: 'skills/ultimate', variants: [svg(GI('lorc', 'fire-ray'))] },
  // Class skill fallbacks — use the class's most iconic skill PNG
  { base: 'skills/barbarian_skill',   variants: [png(SUNDER('Skills', 'whirlwind')), svg(GI('lorc', 'muscle-up'))] },
  { base: 'skills/druid_skill',       variants: [png(SUNDER('Skills', 'pulverize')), svg(GI('lorc', 'wolf-head'))] },
  { base: 'skills/necromancer_skill', variants: [png(SUNDER('Skills', 'bone_spear')), svg(GI('lorc', 'bone-knife'))] },
  { base: 'skills/rogue_skill',       variants: [png(SUNDER('Skills', 'twisting_blades')), svg(GI('lorc', 'hood'))] },
  { base: 'skills/sorcerer_skill',    variants: [png(SUNDER('Skills', 'fireball')), svg(GI('lorc', 'lightning-storm'))] },
  { base: 'skills/spiritborn_skill',  variants: [svg(GI('lorc', 'eagle-emblem'))] }, // no exposed icons
  { base: 'skills/paladin_skill',     variants: [svg(GI('lorc', 'holy-grail'))] },   // no exposed icons
  // Archetypes mapped to real skills
  { base: 'skills/whirlwind', variants: [png(SUNDER('Skills', 'whirlwind')), svg(GI('lorc', 'tornado'))] },
  { base: 'skills/fireball',  variants: [png(SUNDER('Skills', 'fireball')), svg(GI('lorc', 'fireball'))] },
  { base: 'skills/ice',       variants: [png(SUNDER('Skills', 'frost_nova')), svg(GI('lorc', 'frost-emblem'))] },
  { base: 'skills/lightning', variants: [png(SUNDER('Skills', 'chain_lightning')), svg(GI('lorc', 'lightning-bolt'))] },
  { base: 'skills/poison',    variants: [png(SUNDER('Skills', 'poison_imbuement')), svg(GI('lorc', 'poison-cloud'))] },
  { base: 'skills/bone',      variants: [png(SUNDER('Skills', 'bone_spear')), svg(GI('lorc', 'bone-knife'))] },
  { base: 'skills/blood',     variants: [png(SUNDER('Skills', 'blood_surge')), svg(GI('lorc', 'dripping-blade'))] },
  { base: 'skills/storm',     variants: [png(SUNDER('Skills', 'tornado')), svg(GI('lorc', 'lightning-storm'))] },
  { base: 'skills/earth',     variants: [png(SUNDER('Skills', 'landslide')), svg(GI('lorc', 'stone-pile'))] },
  { base: 'skills/shadow',    variants: [png(SUNDER('Skills', 'shadow_imbuement')), svg(GI('lorc', 'shadow-follower'))] },
  { base: 'skills/teleport',  variants: [png(SUNDER('Skills', 'teleport')), svg(GI('lorc', 'portal'))] },
  { base: 'skills/shout',     variants: [png(SUNDER('Skills', 'war_cry')), svg(GI('lorc', 'screaming'))] },
  { base: 'skills/leap',      variants: [png(SUNDER('Skills', 'leap')), svg(GI('delapouite', 'jump-across'))] },
  { base: 'skills/minion',    variants: [png(SUNDER('Skills', 'raise_skeleton')), svg(GI('lorc', 'raise-zombie'))] },
  { base: 'skills/trap',      variants: [png(SUNDER('Skills', 'death_trap')), svg(GI('lorc', 'wolf-trap'))] },
  { base: 'skills/dash',      variants: [png(SUNDER('Skills', 'dash')), svg(GI('lorc', 'sprint'))] },
  { base: 'skills/holy',      variants: [svg(GI('lorc', 'holy-grail'))] }, // paladin not on sunderarmor
  { base: 'skills/corpse',    variants: [png(SUNDER('Skills', 'corpse_explosion')), svg(GI('lorc', 'death-skull'))] },
  { base: 'skills/golem',     variants: [png(SUNDER('Skills', 'golem')), svg(GI('lorc', 'stone-block'))] },
  { base: 'skills/raven',     variants: [png(SUNDER('Skills', 'ravens')), svg(GI('lorc', 'raven'))] },
  { base: 'skills/wolf',      variants: [png(SUNDER('Skills', 'wolves')), svg(GI('lorc', 'wolf-head'))] },
];

const EVENT_SOURCES: Source[] = [
  { base: 'events/helltide',  variants: [svg(GI('lorc', 'burning-embers'))] },
  { base: 'events/worldboss', variants: [svg(GI('lorc', 'cyclops'))] },
  { base: 'events/legion',    variants: [svg(GI('lorc', 'spartan'))] },
  { base: 'events/pit',       variants: [svg(GI('lorc', 'portculis'))] },
  { base: 'events/pvp',       variants: [svg(GI('lorc', 'crossed-swords'))] },
];

const UI_SOURCES: Source[] = [
  { base: 'ui/avatar-placeholder', variants: [svg(GI('lorc', 'cowled'))] },
  { base: 'ui/favicon',            variants: [svg(GI('lorc', 'pentagram-rose'))] },
  { base: 'ui/sword-icon',         variants: [svg(GI('lorc', 'crossed-swords'))] },
  { base: 'ui/skull-icon',         variants: [svg(GI('lorc', 'desert-skull'))] },
  { base: 'ui/potion-icon',        variants: [svg(GI('lorc', 'potion-ball'))] },
];

const ALL_SOURCES: Source[] = [
  ...CLASS_SOURCES,
  ...UNIQUE_SOURCES,
  ...ITEM_SOURCES,
  ...SKILL_SOURCES,
  ...EVENT_SOURCES,
  ...UI_SOURCES,
];

// ───────────────────────────────────────────────────────────────
// Download phase
// ───────────────────────────────────────────────────────────────

interface ManifestEntry {
  key: string;           // base + .ext  (the actual R2 key we'll upload to)
  contentType: string;
  bytes: number;
  localPath: string;
  sourceUrl: string;
  ext: string;
}

async function fetchBuffer(url: string): Promise<Buffer | null> {
  try {
    const res = await fetch(url, { headers: { 'User-Agent': USER_AGENT } });
    if (!res.ok) return null;
    const ab = await res.arrayBuffer();
    if (ab.byteLength < 100) return null;
    return Buffer.from(ab);
  } catch {
    return null;
  }
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  const manifest: ManifestEntry[] = [];
  const failed: { base: string; tried: string[] }[] = [];
  let realD4 = 0;
  let svgFallback = 0;

  console.log(`Downloading ${ALL_SOURCES.length} assets to ${OUT_DIR} …\n`);

  for (const src of ALL_SOURCES) {
    process.stdout.write(`  ${src.base.padEnd(40)} `);
    let got: { buffer: Buffer; variant: Variant } | null = null;
    for (const v of src.variants) {
      const buf = await fetchBuffer(v.url);
      if (buf) {
        got = { buffer: buf, variant: v };
        break;
      }
    }
    if (!got) {
      console.log('✗ all candidates failed');
      failed.push({ base: src.base, tried: src.variants.map((v) => v.url) });
      continue;
    }
    const isD4 =
      got.variant.url.includes('sunderarmor.com') ||
      got.variant.url.includes('wikia.nocookie.net');
    if (isD4) realD4++;
    else svgFallback++;
    const key = `${src.base}.${got.variant.ext}`;
    const dir = join(OUT_DIR, src.base.split('/')[0]);
    await mkdir(dir, { recursive: true }).catch(() => {});
    const localPath = join(dir, `${src.base.split('/').slice(1).join('-')}.${got.variant.ext}`);
    await writeFile(localPath, got.buffer);
    manifest.push({
      key,
      contentType: got.variant.contentType,
      bytes: got.buffer.length,
      localPath,
      sourceUrl: got.variant.url,
      ext: got.variant.ext,
    });
    console.log(`${isD4 ? 'D4' : ' i'}  ${key.padEnd(40)} ${got.buffer.length}b`);
  }

  const manifestPath = join(OUT_DIR, 'manifest.json');
  await writeFile(
    manifestPath,
    JSON.stringify({ manifest, failed }, null, 2),
  );

  const totalBytes = manifest.reduce((sum, e) => sum + e.bytes, 0);
  console.log(
    `\nDone. ${manifest.length} downloaded ` +
      `(${realD4} real D4 + ${svgFallback} game-icons SVG), ` +
      `${failed.length} failed, ` +
      `${(totalBytes / 1024).toFixed(1)} KB total.`,
  );
  console.log(`Manifest: ${manifestPath}`);
  if (failed.length) {
    console.log('\nFailed keys:');
    for (const f of failed) console.log(`  ${f.base}`);
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
