/**
 * Sanctuary Hub — asset download pipeline.
 *
 * Downloads each asset to /tmp/sanctuary-assets/ and writes manifest.json.
 * The companion `upload-assets-curl.sh` (generated by Bash + a Cloudflare
 * API token created via the OAuth MCP) PUTs each file to R2.
 *
 * Why this split: the Cloudflare MCP execute environment blocks ALL
 * outbound fetch() (egress denied — even example.com 403s), so we cannot
 * download assets from inside the MCP runtime. Uploads happen separately
 * via the native R2 API with a 1-hour scoped token.
 *
 * Asset sourcing strategy:
 *   - Class portraits + most skill icons: real D4 game art from
 *     `sunderarmor.com/DIABLO4/...` (d4builds.gg's CDN, public).
 *   - Items, events, UI chrome, and unmapped skill archetypes: game-icons
 *     SVGs (MIT licensed) from github.com/game-icons/icons.
 *
 * Run: tsx scripts/upload-assets.ts
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const OUT_DIR = '/tmp/sanctuary-assets';
const USER_AGENT =
  'Mozilla/5.0 SanctuaryHub/1.0 (fan site, educational capstone project)';

// ───────────────────────────────────────────────────────────────
// URL helpers
// ───────────────────────────────────────────────────────────────

const SUNDER = (folder: string, slug: string) =>
  `https://sunderarmor.com/DIABLO4/${folder}/${slug}.png`;

const GI = (artist: string, slug: string) =>
  `https://raw.githubusercontent.com/game-icons/icons/master/${artist}/${slug}.svg`;

// ───────────────────────────────────────────────────────────────
// Source registry — primary (real D4 PNG, ideally) → fallback (SVG)
// ───────────────────────────────────────────────────────────────

interface Variant {
  url: string;
  ext: 'png' | 'svg' | 'jpg';
  contentType: string;
}

interface Source {
  /** Logical key without extension, e.g. `classes/barbarian`. */
  base: string;
  /** Ordered list of candidates. First successful fetch wins. */
  variants: Variant[];
}

const png = (url: string): Variant => ({ url, ext: 'png', contentType: 'image/png' });
const svg = (url: string): Variant => ({ url, ext: 'svg', contentType: 'image/svg+xml' });

// All 7 classes confirmed at sunderarmor.com/DIABLO4/Classes/2/{lower}.png
const CLASS_SOURCES: Source[] = (
  ['barbarian', 'druid', 'necromancer', 'rogue', 'sorcerer', 'spiritborn', 'paladin'] as const
).map((c) => ({
  base: `classes/${c}`,
  variants: [
    png(SUNDER('Classes/2', c)),
    // SVG fallback — themed game-icons
    svg(GI('lorc', c === 'barbarian' ? 'muscle-up'
        : c === 'druid' ? 'wolf-head'
        : c === 'necromancer' ? 'skull-crack'
        : c === 'rogue' ? 'hood'
        : c === 'sorcerer' ? 'lightning-storm'
        : c === 'spiritborn' ? 'eagle-emblem'
        : 'angel-wings')),
  ],
}));

const ITEM_SOURCES: Source[] = [
  // Item type icons — game-icons (no real D4 source exposes these)
  { base: 'items/weapon',  variants: [svg(GI('lorc', 'broadsword'))] },
  { base: 'items/axe',     variants: [svg(GI('lorc', 'battle-axe'))] },
  { base: 'items/mace',    variants: [svg(GI('lorc', 'spiked-mace'))] },
  { base: 'items/scythe',  variants: [svg(GI('lorc', 'scythe'))] },
  { base: 'items/staff',   variants: [svg(GI('lorc', 'wizard-staff'))] },
  { base: 'items/bow',     variants: [svg(GI('lorc', 'bowman'))] },
  { base: 'items/dagger',  variants: [svg(GI('lorc', 'plain-dagger'))] },
  { base: 'items/wand',    variants: [svg(GI('lorc', 'fairy-wand'))] },
  { base: 'items/helm',    variants: [svg(GI('lorc', 'visored-helm'))] },
  { base: 'items/chest',   variants: [svg(GI('lorc', 'breastplate'))] },
  { base: 'items/gloves',  variants: [svg(GI('delapouite', 'gauntlet'))] },
  { base: 'items/boots',   variants: [svg(GI('lorc', 'boots'))] },
  { base: 'items/pants',   variants: [svg(GI('delapouite', 'leg-armor'))] },
  { base: 'items/offhand', variants: [svg(GI('sbed', 'shield'))] },
  { base: 'items/jewelry', variants: [svg(GI('lorc', 'emerald'))] },
  { base: 'items/amulet',  variants: [svg(GI('lorc', 'gem-pendant'))] },
  { base: 'items/mythic',  variants: [svg(GI('lorc', 'crowned-heart'))] },
  { base: 'items/unique',  variants: [svg(GI('lorc', 'shining-sword'))] },
];

// Skill archetypes mapped to real D4 skill icons where possible.
const SKILL_SOURCES: Source[] = [
  // Generic types — no D4 equivalent, use game-icons
  { base: 'skills/active',   variants: [svg(GI('lorc', 'crossed-swords'))] },
  { base: 'skills/passive',  variants: [svg(GI('sbed', 'shield'))] },
  { base: 'skills/ultimate', variants: [svg(GI('lorc', 'fire-ray'))] },
  // Class skill fallbacks — use the class's most iconic skill PNG
  { base: 'skills/barbarian_skill',   variants: [png(SUNDER('Skills', 'whirlwind')), svg(GI('lorc', 'muscle-up'))] },
  { base: 'skills/druid_skill',       variants: [png(SUNDER('Skills', 'pulverize')), svg(GI('lorc', 'wolf-head'))] },
  { base: 'skills/necromancer_skill', variants: [png(SUNDER('Skills', 'bone_spear')), svg(GI('lorc', 'bone-knife'))] },
  { base: 'skills/rogue_skill',       variants: [png(SUNDER('Skills', 'twisting_blades')), svg(GI('lorc', 'hood'))] },
  { base: 'skills/sorcerer_skill',    variants: [png(SUNDER('Skills', 'fireball')), svg(GI('lorc', 'lightning-storm'))] },
  { base: 'skills/spiritborn_skill',  variants: [svg(GI('lorc', 'eagle-emblem'))] }, // no exposed icons
  { base: 'skills/paladin_skill',     variants: [svg(GI('lorc', 'holy-grail'))] },   // no exposed icons
  // Archetypes mapped to real skills
  { base: 'skills/whirlwind', variants: [png(SUNDER('Skills', 'whirlwind')), svg(GI('lorc', 'tornado'))] },
  { base: 'skills/fireball',  variants: [png(SUNDER('Skills', 'fireball')), svg(GI('lorc', 'fireball'))] },
  { base: 'skills/ice',       variants: [png(SUNDER('Skills', 'frost_nova')), svg(GI('lorc', 'frost-emblem'))] },
  { base: 'skills/lightning', variants: [png(SUNDER('Skills', 'chain_lightning')), svg(GI('lorc', 'lightning-bolt'))] },
  { base: 'skills/poison',    variants: [png(SUNDER('Skills', 'poison_imbuement')), svg(GI('lorc', 'poison-cloud'))] },
  { base: 'skills/bone',      variants: [png(SUNDER('Skills', 'bone_spear')), svg(GI('lorc', 'bone-knife'))] },
  { base: 'skills/blood',     variants: [png(SUNDER('Skills', 'blood_surge')), svg(GI('lorc', 'dripping-blade'))] },
  { base: 'skills/storm',     variants: [png(SUNDER('Skills', 'tornado')), svg(GI('lorc', 'lightning-storm'))] },
  { base: 'skills/earth',     variants: [png(SUNDER('Skills', 'landslide')), svg(GI('lorc', 'stone-pile'))] },
  { base: 'skills/shadow',    variants: [png(SUNDER('Skills', 'shadow_imbuement')), svg(GI('lorc', 'shadow-follower'))] },
  { base: 'skills/teleport',  variants: [png(SUNDER('Skills', 'teleport')), svg(GI('lorc', 'portal'))] },
  { base: 'skills/shout',     variants: [png(SUNDER('Skills', 'war_cry')), svg(GI('lorc', 'screaming'))] },
  { base: 'skills/leap',      variants: [png(SUNDER('Skills', 'leap')), svg(GI('delapouite', 'jump-across'))] },
  { base: 'skills/minion',    variants: [png(SUNDER('Skills', 'raise_skeleton')), svg(GI('lorc', 'raise-zombie'))] },
  { base: 'skills/trap',      variants: [png(SUNDER('Skills', 'death_trap')), svg(GI('lorc', 'wolf-trap'))] },
  { base: 'skills/dash',      variants: [png(SUNDER('Skills', 'dash')), svg(GI('lorc', 'sprint'))] },
  { base: 'skills/holy',      variants: [svg(GI('lorc', 'holy-grail'))] }, // paladin not on sunderarmor
  { base: 'skills/corpse',    variants: [png(SUNDER('Skills', 'corpse_explosion')), svg(GI('lorc', 'death-skull'))] },
  { base: 'skills/golem',     variants: [png(SUNDER('Skills', 'golem')), svg(GI('lorc', 'stone-block'))] },
  { base: 'skills/raven',     variants: [png(SUNDER('Skills', 'ravens')), svg(GI('lorc', 'raven'))] },
  { base: 'skills/wolf',      variants: [png(SUNDER('Skills', 'wolves')), svg(GI('lorc', 'wolf-head'))] },
];

const EVENT_SOURCES: Source[] = [
  { base: 'events/helltide',  variants: [svg(GI('lorc', 'burning-embers'))] },
  { base: 'events/worldboss', variants: [svg(GI('lorc', 'cyclops'))] },
  { base: 'events/legion',    variants: [svg(GI('lorc', 'spartan'))] },
  { base: 'events/pit',       variants: [svg(GI('lorc', 'portculis'))] },
  { base: 'events/pvp',       variants: [svg(GI('lorc', 'crossed-swords'))] },
];

const UI_SOURCES: Source[] = [
  { base: 'ui/avatar-placeholder', variants: [svg(GI('lorc', 'cowled'))] },
  { base: 'ui/favicon',            variants: [svg(GI('lorc', 'pentagram-rose'))] },
  { base: 'ui/sword-icon',         variants: [svg(GI('lorc', 'crossed-swords'))] },
  { base: 'ui/skull-icon',         variants: [svg(GI('lorc', 'desert-skull'))] },
  { base: 'ui/potion-icon',        variants: [svg(GI('lorc', 'potion-ball'))] },
];

const ALL_SOURCES: Source[] = [
  ...CLASS_SOURCES,
  ...ITEM_SOURCES,
  ...SKILL_SOURCES,
  ...EVENT_SOURCES,
  ...UI_SOURCES,
];

// ───────────────────────────────────────────────────────────────
// Download phase
// ───────────────────────────────────────────────────────────────

interface ManifestEntry {
  key: string;           // base + .ext  (the actual R2 key we'll upload to)
  contentType: string;
  bytes: number;
  localPath: string;
  sourceUrl: string;
  ext: string;
}

async function fetchBuffer(url: string): Promise<Buffer | null> {
  try {
    const res = await fetch(url, { headers: { 'User-Agent': USER_AGENT } });
    if (!res.ok) return null;
    const ab = await res.arrayBuffer();
    if (ab.byteLength < 100) return null;
    return Buffer.from(ab);
  } catch {
    return null;
  }
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  const manifest: ManifestEntry[] = [];
  const failed: { base: string; tried: string[] }[] = [];
  let realD4 = 0;
  let svgFallback = 0;

  console.log(`Downloading ${ALL_SOURCES.length} assets to ${OUT_DIR} …\n`);

  for (const src of ALL_SOURCES) {
    process.stdout.write(`  ${src.base.padEnd(40)} `);
    let got: { buffer: Buffer; variant: Variant } | null = null;
    for (const v of src.variants) {
      const buf = await fetchBuffer(v.url);
      if (buf) {
        got = { buffer: buf, variant: v };
        break;
      }
    }
    if (!got) {
      console.log('✗ all candidates failed');
      failed.push({ base: src.base, tried: src.variants.map((v) => v.url) });
      continue;
    }
    const isD4 = got.variant.url.includes('sunderarmor.com');
    if (isD4) realD4++;
    else svgFallback++;
    const key = `${src.base}.${got.variant.ext}`;
    const dir = join(OUT_DIR, src.base.split('/')[0]);
    await mkdir(dir, { recursive: true }).catch(() => {});
    const localPath = join(dir, `${src.base.split('/').slice(1).join('-')}.${got.variant.ext}`);
    await writeFile(localPath, got.buffer);
    manifest.push({
      key,
      contentType: got.variant.contentType,
      bytes: got.buffer.length,
      localPath,
      sourceUrl: got.variant.url,
      ext: got.variant.ext,
    });
    console.log(`${isD4 ? 'D4' : ' i'}  ${key.padEnd(40)} ${got.buffer.length}b`);
  }

  const manifestPath = join(OUT_DIR, 'manifest.json');
  await writeFile(
    manifestPath,
    JSON.stringify({ manifest, failed }, null, 2),
  );

  const totalBytes = manifest.reduce((sum, e) => sum + e.bytes, 0);
  console.log(
    `\nDone. ${manifest.length} downloaded ` +
      `(${realD4} real D4 + ${svgFallback} game-icons SVG), ` +
      `${failed.length} failed, ` +
      `${(totalBytes / 1024).toFixed(1)} KB total.`,
  );
  console.log(`Manifest: ${manifestPath}`);
  if (failed.length) {
    console.log('\nFailed keys:');
    for (const f of failed) console.log(`  ${f.base}`);
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
